(function(){'use strict';
const T=THREE,C=FetalCore,$=id=>document.getElementById(id),V=a=>new T.Vector3(...a);
let params={...C.defaults},result=C.solve(params),running=!matchMedia('(prefers-reduced-motion: reduce)').matches,time=0,last=0,selected='';
try{const old=localStorage.getItem('iso-fetal-lab-v1');if(old)params=C.parse(old);}catch(e){}
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true});}catch(e){$('fetal-load').textContent='La vista 3D richiede WebGL.';return;}
renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;
const stage=$('stage');stage.append(renderer.domElement);const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,80),orbit={theta:.04,phi:1.5,r:15,target:new T.Vector3(-.65,-.15,0)};
scene.add(new T.HemisphereLight(0xcfe6ff,0x6c3e51,.8));const light=new T.DirectionalLight(0xffffff,1.1);light.position.set(-3,6,7);scene.add(light);
const points={placenta:[-3.4,-2.7,.2],uv:[-2.6,-1.75,.4],liver:[-1.5,-1.6,-.2],ivc:[-1,-.60,.1],ra:[-.55,.6,.20],rv:[-.1,.02,.55],pa:[.0,1.30,.45],lungs:[2.65,1.5,-.1],la:[.6,.78,-.3],lv:[.75,.08,.18],aorta:[.8,1.65,.05],descending:[1.45,-.8,-.2],upper:[0,3,.0],svc:[-1.40,1.65,0],lower:[.7,-3.0,.2],uaR:[-1.9,-3.3,.5],uaL:[-2.0,-2.95,-.2],myocardium:[-1.65,.85,1.0],gut:[-.25,-2.2,.8]};
const names={placenta:'Placenta',uv:'Vena ombelicale',liver:'Fegato',ivc:'Vena cava inferiore',ra:'Atrio destro',rv:'Ventricolo destro',pa:'Tronco polmonare',lungs:'Polmoni',la:'Atrio sinistro',lv:'Ventricolo sinistro',aorta:'Aorta ascendente',descending:'Aorta discendente',upper:'Testa e arti superiori',svc:'Vena cava superiore',lower:'Tronco e arti inferiori',uaR:'Arteria ombelicale destra',uaL:'Arteria ombelicale sinistra',myocardium:'Miocardio',gut:'Distretto splancnico'};
const descriptions={coronary:'Il circuito coronarico prende origine dall’aorta e alimenta il miocardio.',coronaryReturn:'Il ritorno coronarico è qui aggregato nel seno coronario verso l’atrio destro.',hepaticArtery:'La componente arteriosa sistemica irrora il fegato anche quando la placenta è esclusa.',mesenteric:'Il distretto splancnico riceve sangue dal circolo arterioso sistemico.',portal:'Il ritorno splancnico attraversa il sistema portale e il fegato prima di raggiungere la vena cava inferiore.',uv:'La singola vena ombelicale trasporta sangue dalla placenta al feto.',dv:'Il dotto venoso collega il ritorno ombelicale alla vena cava inferiore, affiancando il percorso attraverso il fegato.',hepatic:'Una parte del sangue ombelicale perfonde il fegato; il resto può attraversare il dotto venoso.',hepaticReturn:'Il ritorno epatico confluisce nella vena cava inferiore.',ivc:'La vena cava inferiore raccoglie ritorno inferiore, epatico e del dotto venoso.',fo:'Il forame ovale consente il passaggio atrio destro → atrio sinistro nel circuito fetale. Lo streaming preferenziale non è simulato.',tricuspid:'Dall’atrio destro al ventricolo destro, attraverso la tricuspide.',pulmonaryValve:'Dal ventricolo destro al tronco polmonare, attraverso la valvola polmonare.',pulmonary:'Il polmone fetale riceve una parte della gittata destra; la ripartizione cambia con la resistenza impostata.',pulmonaryVeins:'Il ritorno polmonare raggiunge l’atrio sinistro tramite le vene polmonari.',mitral:'Dall’atrio sinistro al ventricolo sinistro, attraverso la mitrale.',aorticValve:'Dal ventricolo sinistro all’aorta, attraverso la valvola aortica.',upper:'L’aorta ascendente distribuisce sangue al distretto superiore.',arch:'Attraverso l’arco aortico il sangue raggiunge l’aorta discendente.',svc:'Il distretto superiore drena nella vena cava superiore.',svcRA:'La vena cava superiore sbocca nell’atrio destro.',lower:'L’aorta discendente perfonde il distretto inferiore.',lowerReturn:'Il distretto inferiore ritorna alla vena cava inferiore.',uaR:'Una delle due arterie ombelicali riporta sangue dal feto alla placenta.',uaL:'La seconda arteria ombelicale completa il ritorno fetoplacentare.',placentaR:'Ritorno della prima arteria ombelicale alla placenta.',placentaL:'Ritorno della seconda arteria ombelicale alla placenta.',da:'Il dotto arterioso collega tronco/arteria polmonare e aorta discendente. La direzione è impostata dal controllo dedicato, non predetta da pressioni simulate.'};
const edgeNames={coronary:'Arterie coronarie',coronaryReturn:'Seno coronario · ritorno aggregato',hepaticArtery:'Arteria epatica',mesenteric:'Arterie splancniche',portal:'Vena porta',uv:'Vena ombelicale',dv:'Dotto venoso di Aranzio',hepatic:'Apporto ombelicale al fegato',hepaticReturn:'Vene epatiche',ivc:'Vena cava inferiore',fo:'Forame ovale',tricuspid:'Valvola tricuspide',pulmonaryValve:'Valvola polmonare',pulmonary:'Arterie polmonari',pulmonaryVeins:'Vene polmonari',mitral:'Valvola mitrale',aorticValve:'Valvola aortica',upper:'Arterie del distretto superiore',arch:'Arco aortico',svc:'Ritorno venoso superiore',svcRA:'Vena cava superiore',lower:'Arterie del distretto inferiore',lowerReturn:'Ritorno venoso inferiore',uaR:'Arteria ombelicale destra',uaL:'Arteria ombelicale sinistra',placentaR:'Ritorno placentare destro',placentaL:'Ritorno placentare sinistro',da:'Dotto arterioso di Botallo'};
const curves={},meshes=[],labels=[],particles=[],shunts=new Set(['dv','fo','da']);let heart=null,available=true;
function label(text,point,special=false){const el=document.createElement('div');el.className='fetal-label'+(special?' special':'');el.textContent=text;$('fetal-labels').append(el);labels.push({el,point:V(point)});return el;}
function mat(color,opacity=1){return new T.MeshStandardMaterial({color:new T.Color(color).convertSRGBToLinear(),roughness:.7,transparent:opacity<1,opacity,depthWrite:opacity===1});}
function organ(key,color,scale){const mesh=new T.Mesh(new T.SphereGeometry(1,32,20),mat(color,.65));mesh.position.copy(V(points[key]));mesh.scale.set(...scale);scene.add(mesh);return mesh;}
organ('placenta','#ab667c',[.48,.68,.19]);organ('liver','#96706c',[.55,.28,.29]);organ('lungs','#7293ac',[.45,.68,.32]);organ('upper','#637e91',[.44,.38,.30]);organ('lower','#637e91',[.5,.28,.22]);organ('gut','#9a857e',[.42,.3,.25]);organ('myocardium','#ac7383',[.18,.24,.16]);
const labelOffsets={placenta:[-.3,-.82,0],uv:[-.2,.10,0],liver:[-.10,-.36,0],ivc:[.10,-.20,0],ra:[-.38,-.12,.3],rv:[-.55,-.4,.2],pa:[-.25,.35,.2],lungs:[.14,.88,0],la:[.75,.43,0],lv:[.50,-.25,.1],aorta:[.13,.3,0],descending:[.60,-.1,0],upper:[0,.48,0],svc:[-.28,.2,0],lower:[.05,-.45,0],uaR:[.10,-.35,0],uaL:[-.2,.30,0],gut:[.42,-.30,0],myocardium:[-.35,.28,0]};
Object.keys(points).forEach(k=>label(names[k],points[k].map((v,i)=>v+(labelOffsets[k]?.[i]||0))));
const routes={coronary:[points.aorta,[-.5,1.85,1.0],points.myocardium],coronaryReturn:[points.myocardium,[-1.4,.4,.6],points.ra],hepaticArtery:[points.descending,[.1,-1.0,-.45],points.liver],mesenteric:[points.descending,[1.0,-1.9,.6],points.gut],portal:[points.gut,[-.8,-2,.45],points.liver],
 uv:[points.placenta,[-3.15,-2.1,.3],points.uv],dv:[points.uv,[-2.0,-.65,.60],points.ivc],hepatic:[points.uv,[-2,-1.7,-.1],points.liver],hepaticReturn:[points.liver,[-1.2,-1.3,-.15],points.ivc],ivc:[points.ivc,[-.9,.1,.15],points.ra],fo:[points.ra,[-.05,.85,.3],points.la],tricuspid:[points.ra,[-.45,.25,.4],points.rv],pulmonaryValve:[points.rv,[-.13,.67,.67],points.pa],pulmonary:[points.pa,[1.1,1.7,-.15],points.lungs],pulmonaryVeins:[points.lungs,[1.9,.60,-.45],points.la],mitral:[points.la,[.65,.3,-.03],points.lv],aorticValve:[points.lv,[.55,.90,.08],points.aorta],upper:[points.aorta,[.6,2.6,.1],points.upper],arch:[points.aorta,[1.2,1.5,-.40],[1.48,.5,-.45],points.descending],svc:[points.upper,[-1.2,2.6,.1],points.svc],svcRA:[points.svc,[-1.2,1.1,.05],points.ra],lower:[points.descending,[1.4,-2.3,-.15],points.lower],lowerReturn:[points.lower,[-.45,-2.7,-.45],points.ivc],uaR:[points.descending,[.9,-2.15,.7],points.uaR],uaL:[points.descending,[.3,-2.6,-.65],points.uaL],placentaR:[points.uaR,[-2.8,-3.25,.5],points.placenta],placentaL:[points.uaL,[-2.7,-2.9,-.2],points.placenta],da:[points.pa,[.62,1.0,.45],[1.17,.68,.1],points.descending]
};
for(const [id,route] of Object.entries(routes)){
 const curve=new T.CatmullRomCurve3(route.map(V));curves[id]=curve;
 const mesh=new T.Mesh(new T.TubeGeometry(curve,60,shunts.has(id)?.052:.031,8,false),mat(shunts.has(id)?'#e4bc75':'#a899be'));
 mesh.userData.id=id;scene.add(mesh);meshes.push(mesh);
 const dots=[];for(let i=0;i<6;i++){const dot=new T.Mesh(new T.SphereGeometry(.04,8,6),new T.MeshBasicMaterial({color:'#ead9ce'}));scene.add(dot);dots.push(dot);}particles.push({id,curve,dots,length:curve.getLength()});
 const op=document.createElement('option');op.value=id;op.textContent=edgeNames[id];$('fetal-path').append(op);
 if(shunts.has(id)){const p=curve.getPointAt(.5);p.z+=.12;if(id==='fo'){p.y+=.26;p.x-=.20;}if(id==='dv')p.x-=.25;if(id==='da')p.x+=.18;label(edgeNames[id],p.toArray(),true);}
}
new T.GLTFLoader().load('heart-z-anatomy.glb',gltf=>{heart=gltf.scene;heart.traverse(o=>{if(o.isMesh){const n=o.userData.sourceName||o.name;o.visible=/^(Right|Left) (atrium|ventricle)$/.test(n);o.material=mat('#ba798b',.18);o.material.side=T.DoubleSide;}});heart.scale.setScalar(.75);heart.position.set(.1,.60,.02);scene.add(heart);$('fetal-load').hidden=true;},undefined,()=>{$('fetal-load').textContent='Cuore anatomico non caricato; il circuito resta esplorabile.';});
const controls=[];
const specs=[['fo','Forame ovale · quota di passaggio',0,.9,.01,'%'],['dv','Dotto venoso · quota di passaggio',0,1,.01,'%'],['da','Dotto arterioso · conduttanza relativa',0,1,.01,'%'],['pvr','Resistenza polmonare relativa',.1,20,.1,'×'],['placenta','Distribuzione placentare',0,.8,.01,'%'],['upper','Distribuzione al distretto superiore',.1,.9,.01,'%'],['oxygenation','Ossigenazione polmonare relativa',0,1,.01,'%'],['extraction','Estrazione periferica convenzionale',0,.4,.01,'%'],['speed','Velocità di visualizzazione',.1,3,.1,'×'],['coronary','Quota aortica al miocardio',0,.2,.01,'%'],['hepatic','Quota sistemica inferiore al fegato',0,.2,.01,'%'],['splanchnic','Quota sistemica inferiore splancnica',0,.4,.01,'%']];
for(const [key,text,min,max,step,unit] of specs){const div=document.createElement('div');div.className='param-row';const title=document.createElement('label');title.textContent=text;const wrap=document.createElement('div');wrap.className='param-inputs';const range=document.createElement('input'),num=document.createElement('input'),u=document.createElement('small');range.type='range';num.type='number';const factor=unit==='%'?100:1;for(const el of [range,num]){el.min=min*factor;el.max=max*factor;el.step=step*factor;el.value=params[key]*factor;el.setAttribute('aria-label',text+(el===range?' · cursore':' · valore'));}u.textContent=unit;wrap.append(range,num,u);div.append(title,wrap);$( ['coronary','hepatic','splanchnic'].includes(key)?'fetal-extra-controls':'fetal-controls').append(div);const change=e=>{if(e.target.value===''||!Number.isFinite(e.target.valueAsNumber))return;params[key]=Math.max(min,Math.min(max,e.target.valueAsNumber/factor));$('fetal-preset').value='';$('preset-note').textContent='Configurazione personalizzata: connessioni e direzioni seguono i parametri impostati.';update();};range.oninput=change;num.oninput=e=>{const v=e.target.valueAsNumber/factor;if(v>=min&&v<=max)change(e);};num.onchange=change;controls.push({key,range,num,factor});}
function config(){return {format:'isoelettrica-fetal-lab',version:1,params};}
function update(){result=C.solve(params);controls.forEach(c=>c.range.value=c.num.value=params[c.key]*c.factor);$('duct-direction').value=params.direction;const rows=$('flow-table').querySelector('tbody');rows.replaceChildren();
 for(const e of result.edges){const tr=document.createElement('tr'),name=document.createElement('td'),val=document.createElement('td');name.textContent=edgeNames[e.id];val.textContent=e.flow.toFixed(1);tr.append(name,val);rows.append(tr);}
 for(const mesh of meshes){const e=result.edges.find(e=>e.id===mesh.userData.id);mesh.material.opacity=e.flow>.01?(selected&&selected!==e.id?.25:.82):.12;mesh.material.transparent=true;mesh.material.depthWrite=false;const c=new T.Color('#7188c0').lerp(new T.Color('#e6867b'),result.oxygen[e.from]);if(shunts.has(e.id)&&selected!==e.id)c.lerp(new T.Color('#ddbb76'),.35);mesh.material.color.copy(c).convertSRGBToLinear();mesh.scale.setScalar(1);}
 $('fetal-json').value=JSON.stringify(config(),null,2);try{localStorage.setItem('iso-fetal-lab-v1',JSON.stringify(config()));}catch(e){}
 describe();
}
function describe(){const box=$('fetal-selection');if(!selected){box.innerHTML='<b>Segui una goccia.</b><p>Una vena ombelicale arriva dalla placenta; due arterie vi ritornano.</p>';return;}const e=result.edges.find(e=>e.id===selected),b=document.createElement('b'),p=document.createElement('p');b.textContent=edgeNames[selected];p.textContent=descriptions[selected]+' Flusso relativo: '+e.flow.toFixed(1)+'.';box.replaceChildren(b,p);}
$('fetal-path').onchange=()=>{selected=$('fetal-path').value;update();};
const presetNotes={fetal:'Tre shunt aperti. Nel dotto arterioso il percorso è polmonare → aorta.',transition:'Schema intermedio con resistenza polmonare ridotta e shunt in chiusura. Non rappresenta una cronologia clinica.',neonatal:'Placenta esclusa e tre passaggi fetali chiusi: circoli polmonare e sistemico in serie.',pda:'Dotto ancora aperto dopo la nascita; direzione imposta aorta → polmonare. Non include altre malformazioni.'};
$('fetal-preset').onchange=()=>{params={...C.presets[$('fetal-preset').value]};$('preset-note').textContent=presetNotes[$('fetal-preset').value];update();};$('preset-note').textContent='Schema configurabile: verifica i valori dei passaggi fetali e la direzione del dotto.';
$('duct-direction').onchange=()=>{params.direction=Number($('duct-direction').value);$('fetal-preset').value='';$('preset-note').textContent='Direzione del dotto impostata manualmente.';update();};
$('fetal-save').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(config(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='isoelettrica-circolazione-fetale.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function apply(raw){params=C.parse(raw);$('fetal-preset').value='';update();$('fetal-error').textContent='Configurazione applicata.';}
$('fetal-apply').onclick=()=>{try{apply($('fetal-json').value);}catch(e){$('fetal-error').textContent='Valori non applicati: '+e.message;}};$('fetal-import').onchange=async()=>{try{const f=$('fetal-import').files[0];if(!f)return;if(f.size>1e5)throw Error('File troppo grande');apply(await f.text());}catch(e){$('fetal-error').textContent=e.message;}};
function playLabel(){$('fetal-play').textContent=running?'Ⅱ Pausa':'▶ Riprendi';$('fetal-play').setAttribute('aria-pressed',String(running));}$('fetal-play').onclick=()=>{running=!running;playLabel();};playLabel();
function resetCamera(){orbit.theta=.04;orbit.phi=1.5;orbit.r=15;}$('fetal-reset-camera').onclick=resetCamera;
const pts=new Map();let moved=0,pinch=null;
stage.addEventListener('pointerdown',e=>{stage.setPointerCapture(e.pointerId);pts.set(e.pointerId,[e.clientX,e.clientY]);moved=0;if(pts.size===2){const a=[...pts.values()];pinch={d:Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]),r:orbit.r};}});
stage.addEventListener('pointermove',e=>{const a=pts.get(e.pointerId);if(!a)return;moved+=Math.abs(e.clientX-a[0])+Math.abs(e.clientY-a[1]);pts.set(e.pointerId,[e.clientX,e.clientY]);if(pts.size===1){orbit.theta-=(e.clientX-a[0])*.006;orbit.phi=Math.max(.3,Math.min(2.8,orbit.phi+(a[1]-e.clientY)*.006));}else if(pinch){const b=[...pts.values()];orbit.r=Math.max(7,Math.min(24,pinch.r*pinch.d/Math.max(1,Math.hypot(b[0][0]-b[1][0],b[0][1]-b[1][1]))));}});
function end(e){if(e.type==='pointerup'&&pts.size===1&&moved<6){const rect=stage.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2),camera);const hit=ray.intersectObjects(meshes,false)[0];if(hit){selected=hit.object.userData.id;$('fetal-path').value=selected;update();}}pts.delete(e.pointerId);pinch=null;}
stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end);stage.addEventListener('wheel',e=>{e.preventDefault();orbit.r=Math.max(7,Math.min(24,orbit.r*Math.exp(e.deltaY*.001)));},{passive:false});
stage.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','Home'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')orbit.theta-=.1;if(e.key==='ArrowRight')orbit.theta+=.1;if(e.key==='ArrowUp')orbit.phi=Math.max(.3,orbit.phi-.1);if(e.key==='ArrowDown')orbit.phi=Math.min(2.8,orbit.phi+.1);if(e.key==='+')orbit.r=Math.max(7,orbit.r-.5);if(e.key==='-')orbit.r=Math.min(24,orbit.r+.5);if(e.key==='Home')resetCamera();});
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=w<600?57:38;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(stage);
function frame(now){requestAnimationFrame(frame);if(document.hidden||!available||window.IsoLabEmbedded?.active===false){last=0;return;}if(last&&running)time+=Math.min(80,now-last)/1000;last=now;
 camera.position.set(orbit.target.x+orbit.r*Math.sin(orbit.phi)*Math.sin(orbit.theta),orbit.target.y+orbit.r*Math.cos(orbit.phi),orbit.target.z+orbit.r*Math.sin(orbit.phi)*Math.cos(orbit.theta));camera.lookAt(orbit.target);
 for(const f of particles){const e=result.edges.find(e=>e.id===f.id),reverse=f.id==='da'&&params.direction<0;for(let i=0;i<f.dots.length;i++){const dot=f.dots[i];dot.visible=e.flow>.05;let u=(time*e.flow*.022*params.speed/f.length+i/f.dots.length)%1;if(reverse)u=1-u;f.curve.getPointAt(u,dot.position);const color=new T.Color('#7483c0').lerp(new T.Color('#ffd0ad'),result.oxygen[e.from]);dot.material.color.copy(color);}}
 for(const l of labels){const p=l.point.clone().project(camera);l.el.hidden=p.z>1||p.z<-1||Math.abs(p.x)>1||Math.abs(p.y)>1;if(!l.el.hidden){l.el.style.left=(p.x*.5+.5)*stage.clientWidth+'px';l.el.style.top=(-p.y*.5+.5)*stage.clientHeight+'px';}}
 renderer.render(scene,camera);
}
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();available=false;running=false;playLabel();$('fetal-load').hidden=false;$('fetal-load').textContent='Vista 3D interrotta: ricarica la pagina.';});
$('fetal-preset').value=Object.keys(C.presets).find(k=>Object.keys(params).every(p=>params[p]===C.presets[k][p]))||'';update();resize();requestAnimationFrame(frame);
})();
