/* Native form values remain authoritative. Desktop menus progressively enhance
   selects; touch devices keep the platform picker and keyboard semantics. */
(function(){
'use strict';
const entries=new Map();let current=null,serial=0,queued=false;
const label=s=>s.getAttribute('aria-label')||Array.from(s.labels||[]).map(l=>l.textContent.trim()).join(' ')||s.title||'Scegli un’opzione';
function sync(s){const e=entries.get(s);if(!e)return;if(e.button.disabled!==s.disabled)e.button.disabled=s.disabled;const text=s.options[s.selectedIndex]?.textContent||'Scegli…';if(e.text.textContent!==text)e.text.textContent=text;const name=label(s)+': '+text;if(e.button.getAttribute('aria-label')!==name)e.button.setAttribute('aria-label',name);if(e.wrapper.hidden!==s.hidden)e.wrapper.hidden=s.hidden;}
function syncAll(){queued=false;for(const [s,e] of entries){if(!s.isConnected){if(current?.s===s)close(false);entries.delete(s);}else sync(s);}}
function schedule(){if(!queued){queued=true;queueMicrotask(syncAll);}}
function close(focus=true){if(!current)return;const c=current;current=null;if(c.menu.hidePopover&&c.menu.matches(':popover-open'))c.menu.hidePopover();c.menu.remove();c.button.setAttribute('aria-expanded','false');c.button.removeAttribute('aria-controls');if(focus&&c.button.isConnected)c.button.focus();}
function place(){if(!current)return;const {button,menu,list,search}=current,r=button.getBoundingClientRect(),vw=document.documentElement.clientWidth||innerWidth,vh=innerHeight;
 const width=Math.min(Math.max(r.width,260),420,vw-16),below=vh-r.bottom-12,above=r.top-12,down=below>=Math.min(280,above),height=Math.min(360,Math.max(100,down?below:above));
 menu.style.width=width+'px';menu.style.maxHeight=height+'px';list.style.maxHeight=Math.max(56,height-(search.hidden?14:62))+'px';menu.style.left=Math.max(8,Math.min(r.left,vw-width-8))+'px';menu.style.top=(down?r.bottom+6:Math.max(8,r.top-menu.getBoundingClientRect().height-6))+'px';
}
function open(s){const e=entries.get(s);if(!e||s.disabled)return;if(current?.s===s){close();return;}close(false);sync(s);
 const menu=document.createElement('div');menu.className='ui-menu';menu.id='ui-menu-'+(++serial);menu.setAttribute('popover','manual');
 const search=document.createElement('input');search.type='search';search.className='ui-menu-search';search.placeholder='Cerca…';search.setAttribute('aria-label','Cerca in '+label(s));search.hidden=s.options.length<12;
 const list=document.createElement('div');list.className='ui-menu-list';list.setAttribute('role','listbox');list.setAttribute('aria-label',label(s));menu.append(search,list);
 (document.fullscreenElement||document.body).append(menu);if(menu.showPopover)try{menu.showPopover();}catch(_){}
 current={s,menu,list,search,...e};e.button.setAttribute('aria-expanded','true');e.button.setAttribute('aria-controls',menu.id);
 function render(){list.replaceChildren();const query=search.value.trim().toLocaleLowerCase();Array.from(s.options).forEach((o,i)=>{if(o.hidden||o.parentElement.hidden||!o.textContent.toLocaleLowerCase().includes(query))return;const b=document.createElement('button');b.type='button';b.className='ui-menu-option';b.setAttribute('role','option');b.setAttribute('aria-selected',String(o.selected));b.disabled=o.disabled||(o.parentElement.tagName==='OPTGROUP'&&o.parentElement.disabled);b.textContent=o.textContent;b.setAttribute('aria-label',o.textContent);b.dataset.index=i;
 b.addEventListener('click',()=>{if(s.disabled||b.disabled)return;const changed=s.selectedIndex!==i;s.selectedIndex=i;if(changed){s.dispatchEvent(new Event('input',{bubbles:true}));s.dispatchEvent(new Event('change',{bubbles:true}));}sync(s);close();});list.append(b);});if(!list.children.length){const empty=document.createElement('div');empty.className='ui-menu-empty';empty.textContent='Nessun risultato';list.append(empty);}place();}
 search.addEventListener('input',render);menu.addEventListener('keydown',ev=>{const rows=Array.from(list.querySelectorAll('button:not(:disabled)'));let i=rows.indexOf(document.activeElement);if(ev.key==='Escape'){ev.preventDefault();ev.stopPropagation();close();return;}if(ev.key==='Tab'){close(false);e.button.focus();return;}if(['ArrowDown','ArrowUp','Home','End'].includes(ev.key)){ev.preventDefault();if(!rows.length)return;i=ev.key==='Home'?0:ev.key==='End'?rows.length-1:ev.key==='ArrowDown'?(i+1)%rows.length:(i<=0?rows.length-1:i-1);rows[i].focus();rows[i].scrollIntoView?.({block:'nearest'});}});
 render();const selected=list.querySelector('[aria-selected=true]:not(:disabled)');if(!search.hidden)search.focus();else (selected||list.querySelector('button:not(:disabled)'))?.focus();selected?.scrollIntoView?.({block:'nearest'});place();
}
function enhance(s){if(entries.has(s)||s.multiple||s.size>1||s.dataset.native!==undefined)return;const wrapper=document.createElement('span');wrapper.className='ui-select';const button=document.createElement('button'),text=document.createElement('span');button.type='button';button.className='ui-select-button';button.setAttribute('aria-haspopup','listbox');button.setAttribute('aria-expanded','false');button.append(text);s.before(wrapper);wrapper.append(s,button);s.classList.add('ui-native');s.tabIndex=-1;s.setAttribute('aria-hidden','true');entries.set(s,{wrapper,button,text});button.addEventListener('click',()=>open(s));button.addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();open(s);}});s.addEventListener('focus',()=>button.focus());s.addEventListener('change',()=>sync(s));sync(s);}
function scan(root){if(root.matches?.('select'))enhance(root);root.querySelectorAll?.('select').forEach(enhance);}
function start(){if(!matchMedia('(pointer: fine)').matches)return;scan(document);
 new MutationObserver(records=>{let changed=false;for(const r of records){if(r.target.closest?.('select')){changed=true;if(current?.s.contains(r.target))close(false);}for(const n of r.addedNodes)if(n.nodeType===1&&!n.closest('.ui-menu'))scan(n);if(Array.from(r.removedNodes).some(n=>n.nodeType===1&&(n.matches?.('select,.ui-select')||n.querySelector?.('select'))))changed=true;}if(changed)schedule();}).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['disabled','selected','label','hidden']});
 document.addEventListener('click',schedule);document.addEventListener('change',schedule);document.addEventListener('reset',()=>setTimeout(syncAll,0));document.addEventListener('pointerdown',e=>{if(current&&!current.menu.contains(e.target)&&!current.button.contains(e.target))close(false);});document.addEventListener('scroll',e=>{if(current&&!current.menu.contains(e.target))close(false);},true);window.addEventListener('resize',()=>close(false));document.addEventListener('fullscreenchange',()=>close(false));}
window.IsoControls={refresh(){scan(document);syncAll();},close};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
