const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const T=require('../three.min.js'),G=require('../atlas-geometry.js'),R=require('../anatomy-refinements.js'),A=require('../cardiac-attachments.js'),M=require('../cardiac-mechanics.js'),L=require('../prototipo-cuore/lab-core.js'),C=require('../congenital-morphology.js');
const V=a=>new T.Vector3(...a),near=(a,b,t=2e-5)=>assert.ok(a.distanceTo(b)<t,`${a.toArray()} != ${b.toArray()}`);
let loaded;function model(){return loaded||=new Promise((resolve,reject)=>{vm.runInNewContext(fs.readFileSync(require.resolve('../gltfloader.js'),'utf8'),{THREE:T,TextDecoder,console});const b=fs.readFileSync(require.resolve('../prototipo-cuore/heart-z-anatomy.glb'));new T.GLTFLoader().parse(b.buffer.slice(b.byteOffset,b.byteOffset+b.length),'',g=>resolve(g.scene),reject);});}
const positions=g=>Array.from({length:g.attributes.position.count},(_,i)=>new T.Vector3().fromBufferAttribute(g.attributes.position,i));
function containsVertex(g,p){return positions(g).some(q=>q.distanceToSquared(p)<1e-10);}
test('Display reconstruction preserves source geometries and creates all three epiaortic origins',async()=>{const scene=await model(),source=G.sourceMeshes(scene),before=source.map(m=>Array.from(m.geometry.attributes.position.array)),meshes=R.apply(G.sourceMeshes(scene),G.material);assert.equal(meshes.length,44);for(const [i,m]of source.entries())assert.deepEqual(Array.from(m.geometry.attributes.position.array),before[i]);for(const m of meshes){assert.ok([...m.geometry.attributes.position.array,...m.geometry.attributes.normal.array].every(Number.isFinite),m.name);}const ao=R.aorta();assert.equal(ao.ports.length,3);for(const port of ao.ports)for(const p of port.ring){assert.ok(containsVertex(port.geometry,p));assert.ok(containsVertex(ao.arch,p)||containsVertex(ao.ascending,p));}assert.equal(R.apply(meshes,G.material),meshes);});
test('Pulmonary venous ostia share exact atrial wall vertices throughout contraction',async()=>{const meshes=R.apply(G.sourceMeshes(await model()),G.material),la=meshes.find(m=>m.name==='Left atrium'),params=L.defaults();for(const d of R.pulmonaryVeins){const m=meshes.find(m=>m.name===d.name);assert.ok(m.userData.ostium.length>20,d.name);for(const p of m.userData.ostium){assert.ok(containsVertex(la.geometry,V(p)),d.name+' atrial boundary');assert.ok(containsVertex(m.geometry,V(p)),d.name+' vein boundary');for(const vent of [0,.5,1])near(V(M.deform(p,{atr:1-vent,vent},params)),V(M.deform(A.nearestPoint(la,V(p)).toArray(),{atr:1-vent,vent},params)));}}assert.ok(A.seamNormals(meshes)>100);});
test('Pulmonary branches preserve their bifurcation boundaries and depart along the opening normals',async()=>{const meshes=R.apply(G.sourceMeshes(await model()),G.material);for(const [name,i]of [['Left pulmonary artery',1],['Right pulmonary artery',2]]){const m=meshes.find(m=>m.name===name);for(const p of G.pulmonaryRings[i])assert.ok(containsVertex(m.geometry,V(p)));const r=G.pulmonaryRings[i].map(V),center=r.reduce((c,p)=>c.add(p),new T.Vector3()).divideScalar(r.length),plane=new T.Vector3().crossVectors(r[1].clone().sub(r[0]),r[2].clone().sub(r[0])).normalize();const ps=positions(m.geometry),mean=ps.reduce((a,p)=>a.add(p),new T.Vector3()).divideScalar(ps.length).sub(center);if(mean.dot(plane)<0)plane.negate();assert.ok(ps.every(p=>p.clone().sub(center).dot(plane)>-2e-5),name+' must not fold behind its ostium');assert.ok(mean.dot(plane)/mean.length()>.55);}});
test('Both duct ends lie on the aortic isthmus and proximal left pulmonary artery in every state',async()=>{const meshes=R.apply(G.sourceMeshes(await model()),G.material),a=meshes.find(m=>m.name==='Aortic arch'),p=meshes.find(m=>m.name==='Left pulmonary artery');for(const r of [.018,.04,.12]){const d=R.ductGeometry(meshes,r);assert.ok(d.a.z<-.85&&d.p.z<-.5);assert.ok(d.a.distanceTo(d.p)>.1);for(const [ring,mesh]of [[d.rings[0],a],[d.rings[1],p]])for(const q of ring){const anchor=A.nearestPoint(mesh,q);near(q,anchor);for(const vent of [0,.5,1])near(V(M.deform(q.toArray(),{atr:.4,vent},L.defaults())),V(M.deform(anchor.toArray(),{atr:.4,vent},L.defaults())));}}});
function rig(id,count=3){const d=R.valveRoots()[id],n=V(d.normal),axis=V([1,0,0]).projectOnPlane(n).normalize();return {...d,center:V(d.center),n,axis,side:new T.Vector3().crossVectors(n,axis),count};}
test('Semilunar pockets keep scalloped insertions fixed, coapt along shared rays and remain below the vessel opening',()=>{for(const id of ['aortic','pulmonary'])for(const count of [2,3]){const r=rig(id,count);for(let leaf=0;leaf<count;leaf++)for(let i=0;i<=20;i++){const u=i/20;near(A.valvePoint(r,leaf,u,0,0),A.valvePoint(r,leaf,u,0,1));if(u>=.5)near(A.valvePoint(r,leaf,u,1,0),A.valvePoint(r,(leaf+1)%count,1-u,1,0));for(const open of [0,.5,1])for(const v of [0,.25,.5,.75,1]){const q=A.valvePoint(r,leaf,u,v,open).sub(r.center),height=q.dot(r.n);assert.ok(height<=.145+1e-6);assert.ok(q.addScaledVector(r.n,-height).length()<=r.radius+1e-6);}}}});
test('Congenital morphologies are reversible, have finite coordinates and restore baseline vessel geometry',async()=>{const meshes=R.apply(G.sourceMeshes(await model()),G.material),anatomy=new T.Group();meshes.forEach(m=>anatomy.add(m));const api={meshes,anatomy,movingMaterial:m=>m},c=C.create(api),original=meshes.map(m=>Array.from(m.geometry.attributes.position.array));for(const [id,d]of Object.entries(C.definitions)){c.set(id,d.max);assert.equal(c.current,id);for(const m of meshes)assert.ok([...m.geometry.attributes.position.array].every(Number.isFinite));if(id==='bicuspid')assert.equal(c.valveCount('aortic'),2);c.set(null);assert.equal(c.current,null);assert.equal(c.extras.length,0);for(const [i,m]of meshes.entries())assert.deepEqual(Array.from(m.geometry.attributes.position.array),original[i]);}const q=V([.165,.96,-1.27]);assert.ok(C.deformAorta(q,.6).distanceTo(V([-.04,.96,-1.27]))<q.distanceTo(V([-.04,.96,-1.27])));});
test('Septal previews cut actual communication through both target walls and reset cleanly',async()=>{const meshes=R.apply(G.sourceMeshes(await model()),G.material),group=new T.Group();meshes.forEach(m=>group.add(m));const c=C.create({meshes,anatomy:group,movingMaterial:m=>m});for(const id of ['asd2','vsdperi','vsdmuscle']){const d=C.definitions[id],n=V(d.normal).normalize(),ray=new T.Raycaster(V(d.center).addScaledVector(n,-d.depth/2),n,0,d.depth),targets=meshes.filter(m=>d.targets.includes(m.name));group.updateMatrixWorld();const before=ray.intersectObjects(targets).length;assert.ok(before>0,id+' intersects the baseline septum');c.set(id,d.def);assert.equal(ray.intersectObjects(targets).length,0,id+' opens the septum');c.set(null);assert.equal(ray.intersectObjects(targets).length,before);}});
test('Dependent anatomy modules load in order in the browser',()=>{const html=fs.readFileSync(require.resolve('../prototipo-cuore/index.html'),'utf8');for(const [a,b]of [['atlas-geometry.js','anatomy-refinements.js'],['anatomy-refinements.js','congenital-morphology.js'],['congenital-morphology.js','lab.js'],['lab.js','viewer.js']])assert.ok(html.indexOf(a)<html.indexOf(b),a+' before '+b);});

test('Physiology reference heart geometry and materials remain unchanged',()=>{const html=fs.readFileSync(require.resolve('../anatomia.html'),'utf8'),section=html.split('/* Cuore di riferimento */')[1].split('/* Sistema di conduzione */')[0];assert.equal(require('node:crypto').createHash('sha256').update(section).digest('hex'),'da0008a46537852d460c4b5f9e727a1ef89bc58be2a75b0126335fe8d2af7b97');});
test('Venous outlets are complete circular lumens even with irregular atrial boundaries',async()=>{const ms=R.apply(G.sourceMeshes(await model()),G.material);for(const d of R.pulmonaryVeins){const g=ms.find(m=>m.name===d.name).geometry,ps=positions(g),edges=new Map(),ix=g.index.array;for(let i=0;i<ix.length;i+=3)for(let j=0;j<3;j++){const a=ix[i+j],b=ix[i+(j+1)%3],key=[Math.min(a,b),Math.max(a,b)].join(':');edges.set(key,(edges.get(key)||0)+1);}const adj=new Map();for(const [key,n]of edges)if(n===1){const [a,b]=key.split(':').map(Number);for(const [x,y]of [[a,b],[b,a]]){if(!adj.has(x))adj.set(x,[]);adj.get(x).push(y);}}assert.ok([...adj.values()].every(a=>a.length===2));const seen=new Set(),loops=[];for(const start of adj.keys()){if(seen.has(start))continue;const loop=[];let at=start,prev=-1;do{seen.add(at);loop.push(ps[at]);const next=adj.get(at).find(x=>x!==prev);prev=at;at=next;}while(at!==start);loops.push(loop);}assert.equal(loops.length,2);const end=V(d.points.at(-1)),ring=loops.sort((a,b)=>a[0].distanceTo(end)-b[0].distanceTo(end))[0],area=new T.Vector3();for(let i=0;i<ring.length;i++){assert.ok(Math.abs(ring[i].distanceTo(end)-d.radius*.9)<2e-5);area.add(new T.Vector3().crossVectors(ring[i].clone().sub(end),ring[(i+1)%ring.length].clone().sub(end)));}assert.ok(area.length()/2/(Math.PI*(d.radius*.9)**2)>.97,d.name+' covers the full outlet');}});
