const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const T=require('../three.min.js'),G=require('../atlas-geometry.js'),R=require('../anatomy-refinements.js'),A=require('../cardiac-attachments.js'),M=require('../cardiac-mechanics.js'),L=require('../prototipo-cuore/lab-core.js'),C=require('../congenital-morphology.js');
const V=a=>new T.Vector3(...a),near=(a,b,t=2e-5)=>assert.ok(a.distanceTo(b)<t,`${a.toArray()} != ${b.toArray()}`);
let loaded;function model(){return loaded||=new Promise((resolve,reject)=>{vm.runInNewContext(fs.readFileSync(require.resolve('../gltfloader.js'),'utf8'),{THREE:T,TextDecoder,console});const b=fs.readFileSync(require.resolve('../prototipo-cuore/heart-z-anatomy.glb'));new T.GLTFLoader().parse(b.buffer.slice(b.byteOffset,b.byteOffset+b.length),'',g=>resolve(g.scene),reject);});}
const positions=g=>Array.from({length:g.attributes.position.count},(_,i)=>new T.Vector3().fromBufferAttribute(g.attributes.position,i));
function containsVertex(g,p){return positions(g).some(q=>q.distanceToSquared(p)<1e-10);}
test('Display reconstruction preserves source geometries and creates all three epiaortic origins',async()=>{const scene=await model(),source=G.sourceMeshes(scene),before=source.map(m=>Array.from(m.geometry.attributes.position.array)),meshes=R.apply(G.sourceMeshes(scene),G.material);assert.equal(meshes.length,44);for(const [i,m]of source.entries())assert.deepEqual(Array.from(m.geometry.attributes.position.array),before[i]);for(const m of meshes){assert.ok([...m.geometry.attributes.position.array,...m.geometry.attributes.normal.array].every(Number.isFinite),m.name);}const ao=R.aorta();assert.equal(ao.ports.length,3);for(const port of ao.ports)for(const p of port.ring){assert.ok(containsVertex(port.geometry,p));assert.ok(containsVertex(ao.arch,p)||containsVertex(ao.ascending,p));}assert.equal(R.apply(meshes,G.material),meshes);});
test('Pulmonary venous ostia share exact atrial wall vertices throughout contraction',async()=>{const meshes=R.apply(G.sourceMeshes(await model()),G.material),la=meshes.find(m=>m.name==='Left atrium'),params=L.defaults();for(const d of R.pulmonaryVeins){const m=meshes.find(m=>m.name===d.name);assert.ok(m.userData.ostium.length>20,d.name);for(const p of m.userData.ostium){assert.ok(containsVertex(la.geometry,V(p)),d.name+' atrial boundary');assert.ok(containsVertex(m.geometry,V(p)),d.name+' vein boundary');for(const vent of [0,.5,1])near(V(M.deform(p,{atr:1-vent,vent},params)),V(M.deform(A.nearestPoint(la,V(p)).toArray(),{atr:1-vent,vent},params)));}}assert.ok(A.seamNormals(meshes)>100);});
test('Pulmonary trunk and both branches form the same smooth continuous arterial wall',async()=>{
 const J=require('../vascular-cuffs.js'),pa=G.pulmonaryAssembly(),ms=R.apply(G.sourceMeshes(await model()),G.material),joined=J.merge(['trunk','junction','left','right'].map(k=>pa[k]));
 for(const [name,k]of [['Pulmonary trunk','trunk'],['Left pulmonary artery','left'],['Right pulmonary artery','right']])assert.deepEqual(ms.find(m=>m.name===name).geometry.attributes.position.array,pa[k].attributes.position.array);
 assert.equal(J.boundaries(joined).length,2,'only the inner and outer proximal rims remain open; distal walls have thickness');
 assert.ok(joined.index.count/3<50000,'bounded display geometry');
});
test('Both duct ends lie on the aortic isthmus and proximal left pulmonary artery in every state',async()=>{const meshes=R.apply(G.sourceMeshes(await model()),G.material),a=meshes.find(m=>m.name==='Aortic arch'),p=meshes.find(m=>m.name==='Left pulmonary artery');for(const r of [.018,.04,.12]){const d=R.ductGeometry(meshes,r);assert.ok(d.a.z<-.85&&d.p.z<-.5);assert.ok(d.a.distanceTo(d.p)>.1);for(const [ring,mesh]of [[d.rings[0],a],[d.rings[1],p]])for(const q of ring){const anchor=A.nearestPoint(mesh,q);near(q,anchor);for(const vent of [0,.5,1])near(V(M.deform(q.toArray(),{atr:.4,vent},L.defaults())),V(M.deform(anchor.toArray(),{atr:.4,vent},L.defaults())));}}});
function rig(id,count=3){const d=R.valveRoots()[id],n=V(d.normal),axis=V([1,0,0]).projectOnPlane(n).normalize();return {...d,center:V(d.center),n,axis,side:new T.Vector3().crossVectors(n,axis),count};}
test('Semilunar pockets keep scalloped insertions fixed, coapt along shared rays and remain below the vessel opening',()=>{for(const id of ['aortic','pulmonary'])for(const count of [2,3]){const r=rig(id,count);for(let leaf=0;leaf<count;leaf++)for(let i=0;i<=20;i++){const u=i/20;near(A.valvePoint(r,leaf,u,0,0),A.valvePoint(r,leaf,u,0,1));if(u>=.5)near(A.valvePoint(r,leaf,u,1,0),A.valvePoint(r,(leaf+1)%count,1-u,1,0));for(const open of [0,.5,1])for(const v of [0,.25,.5,.75,1]){const q=A.valvePoint(r,leaf,u,v,open).sub(r.center),height=q.dot(r.n);assert.ok(height<=.145+1e-6);assert.ok(q.addScaledVector(r.n,-height).length()<=r.radius+1e-6);}}}});
test('Congenital morphologies are reversible, have finite coordinates and restore baseline vessel geometry',async()=>{const meshes=R.apply(G.sourceMeshes(await model()),G.material),anatomy=new T.Group();meshes.forEach(m=>anatomy.add(m));const api={meshes,anatomy,movingMaterial:m=>m},c=C.create(api),original=meshes.map(m=>Array.from(m.geometry.attributes.position.array));for(const [id,d]of Object.entries(C.definitions)){c.set(id,d.max);assert.equal(c.current,id);for(const m of meshes)assert.ok([...m.geometry.attributes.position.array].every(Number.isFinite));if(id==='bicuspid')assert.equal(c.valveCount('aortic'),2);c.set(null);assert.equal(c.current,null);assert.equal(c.extras.length,0);for(const [i,m]of meshes.entries())assert.deepEqual(Array.from(m.geometry.attributes.position.array),original[i]);}const q=V([.165,.96,-1.27]);assert.ok(C.deformAorta(q,.6).distanceTo(V([-.04,.96,-1.27]))<q.distanceTo(V([-.04,.96,-1.27])));});
test('Septal previews cut actual communication through both target walls and reset cleanly',async()=>{const meshes=R.apply(G.sourceMeshes(await model()),G.material),group=new T.Group();meshes.forEach(m=>group.add(m));const c=C.create({meshes,anatomy:group,movingMaterial:m=>m});for(const id of ['asd2','vsdperi','vsdmuscle']){const d=C.definitions[id],n=V(d.normal).normalize(),ray=new T.Raycaster(V(d.center).addScaledVector(n,-d.depth/2),n,0,d.depth),targets=meshes.filter(m=>d.targets.includes(m.name));group.updateMatrixWorld();const before=ray.intersectObjects(targets).length;assert.ok(before>0,id+' intersects the baseline septum');c.set(id,d.def);assert.equal(ray.intersectObjects(targets).length,0,id+' opens the septum');c.set(null);assert.equal(ray.intersectObjects(targets).length,before);}});
test('Dependent anatomy modules load in order in the browser',()=>{const html=fs.readFileSync(require.resolve('../prototipo-cuore/index.html'),'utf8');for(const [a,b]of [['vascular-cuffs.js','pulmonary-arteries.js'],['pulmonary-arteries.js','atlas-geometry.js'],['atlas-geometry.js','anatomy-refinements.js'],['anatomy-refinements.js','congenital-morphology.js'],['congenital-morphology.js','lab.js'],['lab.js','viewer.js']])assert.ok(html.indexOf(a)<html.indexOf(b),a+' before '+b);});

test('Physiology reference heart geometry and materials remain unchanged',()=>{const html=fs.readFileSync(require.resolve('../anatomia.html'),'utf8'),section=html.split('/* Cuore di riferimento */')[1].split('/* Sistema di conduzione */')[0];assert.equal(require('node:crypto').createHash('sha256').update(section).digest('hex'),'da0008a46537852d460c4b5f9e727a1ef89bc58be2a75b0126335fe8d2af7b97');});
test('Venous outlets have circular inner and outer walls without a lumen cap',async()=>{
 const J=require('../vascular-cuffs.js'),ms=R.apply(G.sourceMeshes(await model()),G.material);
 for(const d of R.pulmonaryVeins){const mesh=ms.find(m=>m.name===d.name),g=mesh.geometry,end=V(d.points.at(-1)),loops=J.boundaries(g);assert.equal(loops.length,2,'only the atrial attachments remain open');
  const distal=positions(g).filter(p=>p.distanceTo(end)<d.radius*1.01);for(const r of[d.radius*.92,d.inner*.92]){const ring=distal.filter(p=>Math.abs(p.distanceTo(end)-r)<2e-5);assert.equal(ring.length,64);}
  const outward=end.clone().sub(V(d.points.at(-2))).normalize(),ray=new T.Raycaster(end.clone().addScaledVector(outward,.025),outward.negate(),0,.07);mesh.updateMatrixWorld();assert.equal(ray.intersectObject(mesh).length,0,'terminal lumen stays open');
 }
});

function edgeStats(geometries){
 const J=require('../vascular-cuffs.js'),g=J.merge(geometries),ix=g.index.array,edges=new Map(),directions=new Map();
 for(let i=0;i<ix.length;i+=3)for(let j=0;j<3;j++){const a=ix[i+j],b=ix[i+(j+1)%3],key=[Math.min(a,b),Math.max(a,b)].join(':');edges.set(key,(edges.get(key)||0)+1);directions.set(key,(directions.get(key)||0)+(a<b?1:-1));}
 return {g,loops:J.boundaries(g),nonmanifold:[...edges.values()].filter(n=>n>2).length,reversed:[...directions].filter(([k,s])=>edges.get(k)===2&&s!==0).length};
}
test('Venous sleeves continue the actual inner and outer atrial cuff, without creating adjacent ostia',async()=>{
 const J=require('../vascular-cuffs.js'),source=G.sourceMeshes(await model()).find(m=>m.name==='Left atrium'),ms=R.apply(G.sourceMeshes(await model()),G.material),wall=ms.find(m=>m.name==='Left atrium');
 const assembly=edgeStats([wall.geometry,...ms.filter(m=>/pulmonary vein/.test(m.name)).map(m=>m.geometry)]),before=edgeStats([source.geometry]);
 assert.equal(assembly.loops.length,before.loops.length,'no new open edges or duplicate venous holes');assert.equal(assembly.nonmanifold,0);assert.equal(assembly.reversed,0);
 const areas=loops=>loops.map(r=>J.area(r)).sort((a,b)=>a-b);areas(before.loops).forEach((a,i)=>assert.ok(Math.abs(a-areas(assembly.loops)[i])<1e-5,'preserve AV boundaries'));
 for(const d of R.pulmonaryVeins){const m=ms.find(m=>m.name===d.name),c=m.userData.sourceCuff;assert.ok(c.outer.length>15&&c.inner.length>15,'both surfaces of a real cuff');for(const point of[...c.outer,...c.inner])near(V(point),A.nearestPoint(source,V(point)));
  const center=J.centroid(c.inner.map(V)),normal=V(c.normal).normalize(),neck=J.centroid(m.userData.ostium.slice(0,64).map(V)),offset=neck.clone().sub(center);assert.ok(offset.dot(normal)>.13&&offset.dot(normal)<.15);assert.ok(offset.clone().projectOnPlane(normal).length()<.025,'coaxial myocardial sleeve');
 }
});
test('Pulmonary venous lumens remain unobstructed through the myocardial sleeve',async()=>{
 const J=require('../vascular-cuffs.js'),ms=R.apply(G.sourceMeshes(await model()),G.material),la=ms.find(m=>m.name==='Left atrium');la.updateMatrixWorld();
 for(const d of R.pulmonaryVeins){const m=ms.find(m=>m.name===d.name),c=m.userData.sourceCuff,center=J.centroid(c.inner.map(V)),n=V(c.normal).normalize(),neck=J.centroid(m.userData.ostium.slice(64).map(V)),direction=neck.clone().sub(center).normalize();m.updateMatrixWorld();const ray=new T.Raycaster(center.clone().addScaledVector(direction,.005),direction,0,center.distanceTo(neck)+.04);assert.equal(ray.intersectObjects([la,m]).length,0,d.name+' has no retained lip across its lumen');}
});
test('Inferior caval and pulmonary roots share both myocardial rims at rest and during contraction',async()=>{
 const ms=R.apply(G.sourceMeshes(await model()),G.material),params=L.defaults();
 for(const [vessel,chamber]of [['Inferior vena cava (thoracic part)','Right atrium'],['Pulmonary trunk','Right ventricle']]){const m=ms.find(m=>m.name===vessel),wall=ms.find(m=>m.name===chamber);assert.ok(m.userData.ostium.length>=128);for(const point of m.userData.ostium){const p=V(point),anchor=A.nearestPoint(wall,p);assert.ok(containsVertex(wall.geometry,p));assert.ok(containsVertex(m.geometry,p));for(const vent of[0,.3,.7,1])near(V(M.deform(point,{atr:1-vent,vent},params)),V(M.deform(anchor.toArray(),{atr:1-vent,vent},params)));}}
 const ivc=ms.find(m=>m.name==='Inferior vena cava (thoracic part)'),J=require('../vascular-cuffs.js'),outer=ivc.userData.ostium.slice(0,64).map(V),area=J.area(outer),sourceArea=J.area(ivc.userData.sourceCuff.outer.map(V));assert.ok(area/sourceArea>.85&&area/sourceArea<1.12,'caval diameter follows its myocardial orifice');
});
test('Ventricular outflow reconstruction adds no holes or inverted seams to the source chamber',async()=>{
 const source=G.sourceMeshes(await model()),ms=R.apply(G.sourceMeshes(await model()),G.material);ms.push(G.junctionMesh());
 for(const [chamber,re]of [['Right ventricle',/^(Pulmonary trunk|Left pulmonary artery|Right pulmonary artery|Bifurcatio)/],['Right atrium',/^Inferior vena cava/]]){const before=edgeStats([source.find(m=>m.name===chamber).geometry]),after=edgeStats(ms.filter(m=>m.name===chamber||re.test(m.name)).map(m=>m.geometry));assert.equal(after.loops.length,before.loops.length);assert.equal(after.nonmanifold,before.nonmanifold);assert.equal(after.reversed,before.reversed);}
});
test('All three anatomy entry points load the shared cuff and pulmonary geometry before use',()=>{
 for(const file of['index.html','anatomia.html','prototipo-cuore/index.html']){const html=fs.readFileSync(require.resolve('../'+file),'utf8');let previous=-1;for(const name of['vascular-cuffs.js','pulmonary-arteries.js','atlas-geometry.js','anatomy-refinements.js']){const i=html.indexOf(name);assert.ok(i>previous,file+' '+name);assert.equal(html.indexOf(name,i+1),-1,file+' must load each module once');previous=i;}}
 const worker=fs.readFileSync(require.resolve('../sw.js'),'utf8');for(const name of['vascular-cuffs.js','pulmonary-arteries.js'])assert.ok(worker.includes("'"+name+"'"),'offline shell includes '+name);
});
