const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),crypto=require('node:crypto');
const T=require('../three.min.js'),G=require('../atlas-geometry.js'),Clock=require('../cardiac-clock.js'),E=require('../engine.js'),D=require('../data.js');
const root=path.join(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
function scenario(id){const sc=D.SCENARIOS.find(x=>x.id===id),cfg=sc.build(Object.fromEntries(sc.params.map(p=>[p.k,p.def]))),st=new E.Stream(cfg,17);st.ensure(15000);return {cfg,st};}
test('CardiacClock reads exact ECG events without changing engine events or configuration',()=>{
 for(const id of ['normale','bav3','fv','asistolia','fibrillazione_atriale'].filter(id=>D.SCENARIOS.some(s=>s.id===id))){const {cfg,st}=scenario(id),before=JSON.stringify([st.ev,st.cfg,st.tGen]);for(let t=4000;t<9000;t+=13){const snap=Clock.read(st,t,cfg),around=st.eventsAround(t);assert.equal(snap.onsetP,around.A?.t??null);assert.equal(snap.onsetQRS,around.V?.t??null);assert.ok(Object.isFrozen(snap));if(snap.events.V){assert.ok(Object.isFrozen(snap.events.V.meta));assert.equal(snap.endT,snap.events.V.t+snap.events.V.meta.qt);}if(['fv','asistolia'].includes(id))assert.equal(snap.organized,false);if(id==='bav3')assert.equal(snap.PR,null);}assert.equal(JSON.stringify([st.ev,st.cfg,st.tGen]),before);}
});
test('Clock onset is immediate, RR comes from beats, and AV dissociation never creates a PR',()=>{
 const {cfg,st}=scenario('normale'),v=st.ev.find(e=>e.kind==='V'&&e.t>5000);const at=Clock.read(st,v.t,cfg),before=Clock.read(st,v.t-.01,cfg);assert.equal(at.onsetQRS,v.t);assert.notEqual(before.onsetQRS,v.t);assert.equal(at.sinceQRS,0);assert.equal(at.PR,v.meta.pr);assert.equal(before.nextQRS.t,v.t);assert.equal(at.events.V===v,false);
 const p=Clock.read({ev:[]},0,{mode:'continuous'});assert.equal(p.RR,null);assert.equal(p.cycle,null);assert.equal(p.endT,null);
});
test('Pulmonary junction has three open boundaries and a connected manifold wall',()=>{
 const g=G.pulmonaryJunction(),idx=g.index.array,p=g.attributes.position,edges=new Map(),neighbors=Array.from({length:p.count},()=>new Set());
 for(let i=0;i<idx.length;i+=3)for(let j=0;j<3;j++){let a=idx[i+j],b=idx[i+(j+1)%3],key=[Math.min(a,b),Math.max(a,b)].join(':');edges.set(key,(edges.get(key)||0)+1);neighbors[a].add(b);neighbors[b].add(a);}
 assert.ok([...edges.values()].every(n=>n===1||n===2));let boundary=new Map();for(const [key,n]of edges)if(n===1){const [a,b]=key.split(':').map(Number);if(!boundary.has(a))boundary.set(a,[]);if(!boundary.has(b))boundary.set(b,[]);boundary.get(a).push(b);boundary.get(b).push(a);}assert.ok([...boundary.values()].every(a=>a.length===2));
 const seen=new Set();let loops=0;for(const start of boundary.keys()){if(seen.has(start))continue;loops++;const stack=[start];while(stack.length){const i=stack.pop();if(seen.has(i))continue;seen.add(i);stack.push(...boundary.get(i));}}
 assert.equal(loops,3);assert.equal(p.count-edges.size+idx.length/3,-1);assert.ok([...p.array,...g.attributes.normal.array].every(Number.isFinite));assert.ok(idx.length/3<4000);
});
let gltfPromise;function model(){if(!gltfPromise)gltfPromise=new Promise((resolve,reject)=>{const context={THREE:T,TextDecoder,console};vm.runInNewContext(read('gltfloader.js'),context);const b=fs.readFileSync(path.join(root,'prototipo-cuore/heart-z-anatomy.glb'));new T.GLTFLoader().parse(b.buffer.slice(b.byteOffset,b.byteOffset+b.length),'',resolve,reject);});return gltfPromise;}
async function environment(){const modelData=await model(),map=JSON.parse(read('prototipo-cuore/atlas-coronary-map.json')),THREE={...T,GLTFLoader:class{load(url,success){queueMicrotask(()=>success(modelData));}}};const ctx={THREE,HeartAtlasGeometry:G,CardiacClock:Clock,URL,console,document:{currentScript:{src:'https://example.test/Isoelettrica/heart-atlas.js?v=43.0'}},fetch:async()=>({ok:true,json:async()=>map})};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(read('cuore3d.js'),ctx);vm.runInContext(read('heart-atlas.js'),ctx);return {ctx,map};}
test('ECG and Coronarie share the full atlas; all 17 existing territory controls remain renderable',async()=>{
 const {ctx,map}=await environment(),a=ctx.HeartAtlas.build({opacity:.7}),b=ctx.HeartAtlas.build({coronary:true});await Promise.all([a.ready,b.ready]);assert.ok(a.loaded&&b.loaded);assert.equal(a.meshes.length,40);assert.equal(a.group.scale.x,.65);assert.ok(a.meshes.every(m=>m.material.opacity===.7));
 for(let i=1;i<=17;i++)assert.ok(b.seg[i].geometry.attributes.position.count>0,'AHA '+i);
 assert.ok(b.rv.geometry.attributes.position.count>0);for(const id of map.keys){assert.ok(b.coro[id]?.material);const v=ctx.ISO_CUORE.CORO[id].via;assert.ok(v.length>1&&v.every(p=>p.length===4&&p[3]==='w'&&p.slice(0,3).every(Number.isFinite)),id);}
 for(const [name,faces]of Object.entries(map.faces)){assert.ok(faces.length>0);assert.ok(faces.every(i=>i>=0&&i<map.keys.length));}
 assert.equal(map.sourceSha256,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'prototipo-cuore/heart-z-anatomy.glb'))).digest('hex'));
 b.setTissueOpacity(.2,true);for(const m of b.meshes){if(m.userData.layer==='coronaries'){assert.equal(m.material.opacity,1);assert.equal(m.material.depthTest,false);}else assert.equal(m.material.opacity,.2);}for(const id of map.reconstructed)assert.equal(b.coro[id].material.depthTest,false,id);b.setTissueOpacity(1,false);assert.ok(b.meshes.every(m=>m.material.opacity===1&&m.material.depthTest));
 const original=await model();assert.equal(G.sourceMeshes(original.scene).length,39);a.setOpacity(1);assert.ok(a.meshes.every(m=>!m.material.transparent&&m.material.depthWrite));
});
test('Navigation preserves the old vector laboratory and adds separate adult/fetal pages',()=>{
 const {environment}=require('./harness.cjs'),h=environment();h.w.eval(read('anatomy-host.js'));const d=h.w.document;assert.equal(d.querySelector('[data-v="anat"]').textContent,'Fisiologia');assert.equal(d.querySelector('[data-v="heart"]').textContent,'Anatomia');h.w.IsoAnatomyHost.show('heart');const adult=d.getElementById('heartFrame');assert.equal(adult.getAttribute('src'),'prototipo-cuore/index.html');d.querySelector('[data-heart-page="fetal"]').click();const fetal=d.getElementById('fetalFrame');assert.equal(fetal.getAttribute('src'),'prototipo-cuore/fetale.html');assert.equal(adult.hidden,true);d.querySelector('[data-heart-page="adult"]').click();assert.equal(adult.hidden,false);assert.equal(fetal.hidden,true);assert.equal(d.querySelectorAll('#heartFrame').length,1);h.close();
});
test('Protected engine/data and original atlas hashes match the recorded baseline',()=>{const state=read('STATO.md');for(const f of ['engine.js','data.js','ipertrofie.js','quiz.js','atlante-digitale.js','ptbxl.js','prototipo-cuore/heart-z-anatomy.glb']){const sha=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex');assert.ok(state.includes('| '+f+' | '+sha+' |'),f);}});
