const test=require('node:test'),assert=require('node:assert/strict'),T=require('../three.min.js'),M=require('../cardiac-mechanics.js'),A=require('../cardiac-attachments.js'),C=require('../prototipo-cuore/lab-core.js'),E=require('../engine.js'),D=require('../data.js');
const near=(a,b,tol=1e-6)=>assert.ok(Math.abs(a-b)<tol,`${a} != ${b}`),V=a=>new T.Vector3(...a);
function determinant(q,m,p,regions=[]){const a=[0,1,2].map(i=>{const lo=[...q],hi=[...q];lo[i]-=.001;hi[i]+=.001;const l=M.deform(lo,m,p,regions),h=M.deform(hi,m,p,regions);return h.map((v,j)=>(v-l[j])/.002);});return a[0][0]*(a[1][1]*a[2][2]-a[1][2]*a[2][1])-a[1][0]*(a[0][1]*a[2][2]-a[0][2]*a[2][1])+a[2][0]*(a[0][1]*a[1][2]-a[0][2]*a[1][1]);}
test('Damped elastic response dissipates energy and preserves inertia',()=>{let q={x:1,v:0},energy=Infinity;for(let i=0;i<500;i++){q=M.spring(q.x,q.v,0,.004,40,1);const next=q.v*q.v+1600*q.x*q.x;assert.ok(next<=energy+1e-8);energy=next;}assert.ok(Math.abs(q.x)<1e-20);const first=M.spring(0,0,1,.004,40);assert.ok(first.x>0&&first.x<1&&first.v>0);});
test('Mechanics are independent of display frame rate; pause and backward seek are deterministic',()=>{const p=C.defaults(),target=t=>({atr:Math.max(0,Math.sin(t/170)),vent:Math.max(0,Math.sin(t/130)),valves:{mitral:t%800>400?1:0,tricuspid:.5,aortic:0,pulmonary:1},fibr:0});const slow=M.createDynamics(),fast=M.createDynamics(),direct=M.createDynamics();for(let t=0;t<2300;t+=33)slow.sample(t,target,p);for(let t=0;t<2300;t+=7)fast.sample(t,target,p);const a=slow.sample(2331,target,p),b=fast.sample(2331,target,p),c=direct.sample(2331,target,p);near(a.vent,b.vent);near(a.vent,c.vent,1e-5);assert.deepEqual(a,slow.sample(2331,target,p));const back=slow.sample(1100,target,p),fresh=M.createDynamics().sample(1100,target,p);near(back.vent,fresh.vent);});
test('Every existing ECG remains finite and read-only under extreme elastic controls',()=>{for(const sc of D.SCENARIOS){const p=C.defaults();p['mechanics.stiffness']=3;p['mechanics.damping']=.7;const cfg=sc.build(Object.fromEntries(sc.params.map(p=>[p.k,p.def]))),stream=new E.Stream(cfg,17);stream.ensure(10000);const before=JSON.stringify(stream.ev),solver=M.createDynamics();for(let t=5000;t<5800;t+=27){const m=solver.sample(t,x=>C.sample(stream.eventsAround(x),x,{...cfg,isoClinical:true},p),p);for(const x of [m.atr,m.vent,...Object.values(m.valves).filter(v=>v!==null)])assert.ok(Number.isFinite(x)&&x>=0&&x<=1,sc.id);if(cfg.cont==='vf'||cfg.mode==='continuous')assert.equal(m.vent,0);}assert.equal(JSON.stringify(stream.ev),before);}});
test('Shared spatial deformation avoids folds at editable contraction bounds, including overlapping damage',()=>{const p={...C.defaults(),'muscle.atrial':.25,'muscle.vent':.3,'muscle.long':.2,'muscle.twist':20},r={type:'necrosis',center:[.7,-.55,.6],radius:.02,strength:1};for(const regions of [[],[r],Array(32).fill(r)])for(let x=-1.2;x<1.4;x+=.26)for(let y=-1.3;y<1.5;y+=.26)for(let z=-1.2;z<1.1;z+=.26)assert.ok(determinant([x,y,z],{atr:1,vent:1},p,regions)>.05);});
test('Deformed normals stay perpendicular to the transformed surface',()=>{const q=[.6,-.4,.3],n=[0,1,0],m={atr:.4,vent:.9},p=C.defaults(),nn=M.normal(q,n,m,p);near(Math.hypot(...nn),1);for(const dir of [[1,0,0],[0,0,1]]){const lo=M.deform(q.map((x,i)=>x-dir[i]*.0005),m,p),hi=M.deform(q.map((x,i)=>x+dir[i]*.0005),m,p);near(nn.reduce((s,v,i)=>s+v*(hi[i]-lo[i]),0),0,1e-7);}});
function rig(count=2){const n=V([0,1,0]),axis=V([1,0,0]);return {center:V([.3,0,0]),n,axis,side:new T.Vector3().crossVectors(n,axis),radius:.3,count,pap:[[.4,-.7,.1],[.1,-.7,-.1],[.2,-.8,.1]]};}
test('Valve hinges and commissures stay coincident; closed free edges coapt exactly',()=>{const p=C.defaults();for(const count of [2,3])for(const vent of [0,.5,1]){const r=rig(count),deform=q=>V(M.deform(q.toArray(),{atr:.2,vent},p));for(let leaf=0;leaf<count;leaf++)for(const open of [0,.3,1]){for(const v of [0,.5,1]){const a=A.constrainedLeaf(r,leaf,1,v,open,deform,M.tether),b=A.constrainedLeaf(r,(leaf+1)%count,0,v,open,deform,M.tether);assert.ok(a.distanceTo(b)<1e-6);}for(const u of [.25,.5,.75]){const hinge=A.constrainedLeaf(r,leaf,u,0,open,deform,M.tether),expected=deform(A.valvePoint(r,leaf,u,0,0));assert.ok(hinge.distanceTo(expected)<1e-6);if(open===0)assert.ok(A.constrainedLeaf(r,leaf,u,1,0,deform,M.tether).distanceTo(deform(r.center))<1e-6);}}}});
test('Free leaflet points cannot stretch their chord beyond the attached closed configuration',()=>{const r=rig(),p={...C.defaults(),'muscle.vent':.3,'muscle.twist':20};for(const vent of [0,1])for(const open of [.2,.8,1])for(let leaf=0;leaf<2;leaf++){const deform=q=>V(M.deform(q.toArray(),{atr:.3,vent},p)),pap=deform(V(r.pap[leaf]));for(const u of [.25,.5,.75]){const q=A.constrainedLeaf(r,leaf,u,1,open,deform,M.tether),max=deform(A.valvePoint(r,leaf,u,1,0)).distanceTo(pap);assert.ok(q.distanceTo(pap)<=max+1e-5);}}});
test('Picking follows the visible deformed surface and maps painting back to rest coordinates',()=>{const mesh=new T.Mesh(new T.PlaneGeometry(1,1),new T.MeshBasicMaterial({side:T.DoubleSide})),original=Array.from(mesh.geometry.attributes.position.array);mesh.updateMatrixWorld();const ray=new T.Raycaster(V([2,0,3]),V([0,0,-1])),hit=A.pick(ray,[mesh],p=>p.add(V([2,0,0])))[0];assert.equal(hit.object,mesh);near(hit.point.x,2);near(hit.restPoint.x,0);assert.deepEqual(Array.from(mesh.geometry.attributes.position.array),original);});
test('Nearest papillary anchor lies on the actual attachment surface',()=>{const mesh=new T.Mesh(new T.SphereGeometry(.2,16,12)),point=V([.5,.1,.1]),anchor=A.nearestPoint(mesh,point),again=A.nearestPoint(mesh,anchor);assert.ok(anchor.distanceTo(again)<1e-6);assert.ok(anchor.distanceTo(point)<point.length());});
test('Picking never selects an invisible conduction group through the heart',()=>{const group=new T.Group(),mesh=new T.Mesh(new T.PlaneGeometry(1,1),new T.MeshBasicMaterial({side:T.DoubleSide}));group.add(mesh);group.visible=false;group.updateMatrixWorld();const ray=new T.Raycaster(V([0,0,3]),V([0,0,-1]));assert.equal(A.pick(ray,[mesh],p=>p).length,0);group.visible=true;assert.ok(A.pick(ray,[mesh],p=>p).length>0);});
test('Localized stiffness changes do not invert the posterior wall at maximum contraction',()=>{let seed=1;const random=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296),p={...C.defaults(),'muscle.atrial':.25,'muscle.vent':.3,'muscle.long':.2,'muscle.twist':20};for(let i=0;i<5000;i++){const q=[random()*2.6-1.3,random()*3.3-1.5,random()*2.7-1.4],regions=Array.from({length:3},()=>({type:'necrosis',center:q.map(x=>x+(random()-.5)*2.6),radius:.02,strength:1}));assert.ok(determinant(q,{atr:random(),vent:1},p,regions)>.02);}});
