const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const C=require('../conduction-model.js'),K=require('../pathology-catalog.js'),Clock=require('../cardiac-clock.js'),E=require('../engine.js'),D=require('../data.js'),T=require('../three.min.js');
function scenario(id,params={}){const sc=D.SCENARIOS.find(s=>s.id===id),p={...Object.fromEntries(sc.params.map(p=>[p.k,p.def])),...params},cfg=C.configure(id,sc.build(p),p),st=new E.Stream(cfg,41);st.ensure(15000);return {cfg,st};}
test('All existing ECG cases yield finite, read-only conduction plans',()=>{for(const sc of D.SCENARIOS){const {cfg,st}=scenario(sc.id),before=JSON.stringify([cfg,st.ev]);for(let t=3000;t<7500;t+=43){const p=C.plan(Clock.read(st,t,cfg),cfg);for(const [id,a]of Object.entries(p.active)){assert.ok(Number.isFinite(a.u)&&a.u>=0&&a.u<=1,sc.id+':'+id);}if(cfg.cont==='vf'||cfg.mode==='continuous')assert.equal(Object.keys(p.active).length,0);}assert.equal(JSON.stringify([cfg,st.ev]),before,sc.id);}});
test('His travels before its own conducted QRS, never across an unrelated future beat',()=>{const {cfg,st}=scenario('normale'),v=st.ev.find(e=>e.kind==='V'&&e.t>5000),before=C.plan(Clock.read(st,v.t-20,cfg),cfg),after=C.plan(Clock.read(st,v.t+250,cfg),cfg);assert.ok(before.active.his);assert.ok(!after.active.his&&!after.active.fast);const at=C.plan(Clock.read(st,v.t,cfg),cfg);assert.equal(at.active.rb.u,0);});
test('BAV III does not conduct atrial impulses to His; escape beats remain independent',()=>{const {cfg,st}=scenario('bav3');const a=st.ev.find(e=>e.kind==='A'&&e.t>5000);assert.ok(a.meta.blocked);for(let dt=100;dt<190;dt+=10){const snap=Clock.read(st,a.t+dt,cfg),plan=C.plan(snap,cfg);if(snap.sinceQRS>40)assert.ok(!plan.active.his);}assert.equal(C.plan(Clock.read(st,a.t+140,cfg),cfg).nodeBlocked,true);});
test('AVNRT and AVRT use distinct limbs and opposite directions',()=>{for(const id of ['avnrt','avrt','avrtanti']){const {cfg,st}=scenario(id),v=st.ev.find(e=>e.kind==='V'&&e.t>5000),p=C.plan(Clock.read(st,v.t+(id==='avnrt'?20:65),cfg),cfg);if(id==='avnrt'){assert.equal(p.active.fast.reverse,true);assert.equal(p.visible.kent,false);}if(id==='avrt'){assert.equal(p.active.kent.reverse,true);assert.equal(p.visible.kent,true);}if(id==='avrtanti'){assert.equal(p.active.his.reverse,true);assert.ok(!p.active.rb);}}});
test('Fascicular blocks do not animate an intact Purkinje branch downstream',()=>{for(const [id,list]of [['bbdx',['rb']],['bbsx',['laf','lpf','lsf']],['bifascicolare',['rb','laf']]]){const {cfg,st}=scenario(id),v=st.ev.find(e=>e.kind==='V'&&e.t>5000);const p=C.plan(Clock.read(st,v.t+30,cfg),cfg);assert.deepEqual(p.blocked,list);for(const b of list){assert.ok(!p.active[b]);assert.ok(!p.active['pk-'+b+'-0']);}}});
test('Kent location changes added QRS data without mutating source presets; orthodromic remains narrow',()=>{const sc=D.SCENARIOS.find(s=>s.id==='wpw'),raw=sc.build(Object.fromEntries(sc.params.map(p=>[p.k,p.def]))),before=JSON.stringify(raw),values=[];for(const site of C.sites){const c=C.configure('wpw',raw,{kentSite:site.id});values.push(c.qrs.c[0].d.join(','));assert.equal(c.qrs.w,raw.qrs.w);assert.equal(c.pr,raw.pr);assert.ok(C.kent(site.id).points.every(p=>p.every(Number.isFinite)));}assert.equal(new Set(values).size,C.sites.length);assert.equal(JSON.stringify(raw),before);assert.deepEqual(C.configure('wpw',raw,{}).qrs,raw.qrs);const {cfg}=scenario('avrt',{kentSite:'right-lateral'});assert.ok(!cfg.qrs?.delta);});
test('James is opt-in and never adds a delta wave to LGL',()=>{const a=scenario('lgl'),b=scenario('lgl',{jamesModel:'james'});assert.equal(C.mode(a.cfg),'normal');assert.equal(C.mode(b.cfg),'james');assert.deepEqual(a.cfg.qrs,b.cfg.qrs);assert.ok(!b.cfg.qrs.delta);});
test('Changing Kent reuses selectable mesh, disposes geometry and follows the common scale',()=>{const ctx={window:null,THREE:T,IsoConduction:C};ctx.window=ctx;vm.runInNewContext(fs.readFileSync(require.resolve('../conduction-view.js'),'utf8'),ctx);const view=ctx.IsoConductionView.create({scale:.65}),mesh=view.paths.get('kent').tube,old=mesh.geometry;let disposed=false;old.addEventListener('dispose',()=>disposed=true);view.setScenario({isoKent:'right-lateral'});assert.equal(view.paths.get('kent').tube,mesh);assert.equal(disposed,true);assert.equal(view.group.scale.x,.65);const route=view.paths.get('ventricular-return');assert.deepEqual(route.points[0],C.anchors.bif);assert.deepEqual(route.points.at(-1),C.site('right-lateral').ventricular);assert.deepEqual(view.paths.get('his').points,C.paths.find(p=>p.id==='his').points);});
test('Catalog includes every preexisting ECG scenario and labels unimplemented lesion geometry honestly',()=>{const list=K.catalog(D.SCENARIOS);assert.equal(new Set(list.map(c=>c.id)).size,list.length);for(const sc of D.SCENARIOS.filter(s=>s.id!=='normale'))assert.ok(list.some(c=>c.scenario===sc.id));assert.equal(list.length,172);assert.equal(K.structural.filter(c=>c.preview==='structural').length,7);assert.equal(K.structural.filter(c=>c.preview==='localization').length,55);assert.equal(K.structural.filter(c=>c.preview.startsWith('valve')).length,8);assert.ok(K.structural.every(c=>c.target&&c.description));});
test('Pathology mechanics follow the ECG RR and AF/flutter have no organized atrial kick',()=>{const L=require('../prototipo-cuore/lab-core.js');for(const id of ['avnrt','fa','flutter']){const {cfg,st}=scenario(id),v=st.ev.find(e=>e.kind==='V'&&e.t>5000),ev=st.eventsAround(v.t+90),m=L.sample(ev,v.t+90,{...cfg,isoClinical:true},L.defaults());assert.equal(m.total,v.meta.rr);if(['fa','flutter'].includes(id))assert.equal(m.atr,0);}});
test('Kent menu updates the actual ECG case and retains the position across scenario changes',t=>{const h=require('./harness.cjs').app({conduction:true});t.after(h.close);const {A,w}=h;A.loadScenario('wpw',false);const select=w.document.querySelector('[aria-label="Sede della via di Kent"]');assert.ok(select);assert.equal(select.options.length,10);select.value='right-lateral';select.dispatchEvent(new w.Event('change',{bubbles:true}));h.advance(200);assert.equal(A.curCfg.isoKent,'right-lateral');A.loadScenario('avrt',false);assert.ok(!A.curCfg.qrs?.delta);A.loadScenario('wpw',false);assert.equal(A.curCfg.isoKent,'right-lateral');assert.equal(h.errors.length,0);});
test('Pulmonary reconstruction preserves an open central lumen instead of Laplacian collapse',()=>{const G=require('../atlas-geometry.js'),g=G.pulmonaryJunction(),p=g.attributes.position;const top=new T.Vector3().fromBufferAttribute(p,0),bottom=new T.Vector3().fromBufferAttribute(p,1);assert.ok(Math.abs(top.distanceTo(bottom)-.42)<1e-6);const normal=top.clone().sub(bottom).normalize(),center=top.clone().add(bottom).multiplyScalar(.5),mesh=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));mesh.updateMatrixWorld();const ray=new T.Raycaster(center,normal,0,.6);assert.ok(ray.intersectObject(mesh).some(h=>h.distance>.18));normal.negate();ray.set(center,normal);assert.ok(ray.intersectObject(mesh).some(h=>h.distance>.18));});
