const test=require('node:test'),assert=require('node:assert/strict');
const {environment,app,read}=require('./harness.cjs');
async function setup(html){const h=environment();h.w.document.body.innerHTML=html;h.w.matchMedia=()=>({matches:true});h.w.eval(read('ui-surface.js'));h.w.document.dispatchEvent(new h.w.Event('DOMContentLoaded'));await Promise.resolve();return h;}
test('Menu: ricerca, selezione e cambio emessi una volta con il valore nativo',async t=>{
 const h=await setup('<label for="s">Struttura</label><select id="s">'+Array.from({length:15},(_,i)=>'<option value="v'+i+'">Struttura '+i+'</option>').join('')+'</select>');t.after(h.close);const d=h.w.document,s=d.getElementById('s');let changes=0,inputs=0;s.addEventListener('change',()=>changes++);s.addEventListener('input',()=>inputs++);
 d.querySelector('.ui-select-button').click();const search=d.querySelector('.ui-menu-search');assert.equal(search.hidden,false);search.value='Struttura 12';search.dispatchEvent(new h.w.Event('input'));assert.equal(d.querySelectorAll('.ui-menu-option').length,1);d.querySelector('.ui-menu-option').click();await Promise.resolve();assert.equal(s.value,'v12');assert.equal(changes,1);assert.equal(inputs,1);assert.match(d.querySelector('.ui-select-button').textContent,/Struttura 12/);assert.equal(d.querySelector('.ui-menu'),null);assert.equal(d.activeElement,d.querySelector('.ui-select-button'));
 // Repeated refreshes must settle, not recursively create mutation updates.
 for(let i=0;i<5;i++){h.w.IsoControls.refresh();await Promise.resolve();}assert.equal(d.querySelectorAll('.ui-select').length,1);
});
test('Menu: tastiera, annullamento, controlli disabilitati e opzioni dinamiche',async t=>{
 const h=await setup('<select aria-label="Ritmo"><option>A</option><option disabled>B</option><option>C</option></select>');t.after(h.close);const d=h.w.document,s=d.querySelector('select'),button=d.querySelector('.ui-select-button');button.click();const first=d.querySelector('.ui-menu-option');first.dispatchEvent(new h.w.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));assert.equal(d.activeElement.textContent,'C');d.activeElement.dispatchEvent(new h.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(s.value,'A');assert.equal(d.activeElement,button);
 s.disabled=true;await Promise.resolve();await Promise.resolve();assert.equal(button.disabled,true);s.disabled=false;s.innerHTML='<option>X</option><option selected>Y</option>';await Promise.resolve();await Promise.resolve();assert.match(button.textContent,/Y/);button.click();assert.equal(d.querySelectorAll('.ui-menu-option').length,2);assert.equal(d.querySelector('[aria-selected=true]').textContent,'Y');
});
test('Menu: dispositivi touch conservano il selettore della piattaforma',()=>{const h=environment();try{h.w.document.body.innerHTML='<select><option>A</option></select>';h.w.eval(read('ui-surface.js'));h.w.document.dispatchEvent(new h.w.Event('DOMContentLoaded'));assert.equal(h.w.document.querySelector('.ui-select'),null);assert.equal(h.w.document.querySelector('select').hasAttribute('aria-hidden'),false);}finally{h.close();}});
test('Teoria: schermo intero ed Escape non cambiano tema o capitolo',t=>{const h=app();t.after(h.close);const {w,A}=h,d=w.document;d.documentElement.dataset.theme='light';A.showView('theory');const content=d.getElementById('article').innerHTML;d.getElementById('thFull').click();assert.ok(d.body.classList.contains('theory-focus'));assert.equal(d.documentElement.dataset.theme,'light');d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.body.classList.contains('theory-focus'),false);assert.equal(d.getElementById('article').innerHTML,content);});
test('Cuore: focus reversibile senza Fullscreen API e senza ricreare la scena',t=>{const h=environment();t.after(h.close);const {w}=h,d=w.document;d.body.innerHTML='<section class="viewer"><canvas></canvas></section>';const canvas=d.querySelector('canvas');w.eval(read('lab-ui.js'));d.dispatchEvent(new w.Event('DOMContentLoaded'));const b=d.querySelector('.lab-focus-button');b.click();assert.equal(b.getAttribute('aria-pressed'),'true');assert.ok(d.querySelector('.is-model-focus'));d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(b.getAttribute('aria-pressed'),'false');assert.equal(d.querySelector('canvas'),canvas);assert.equal(d.querySelector('.is-model-focus'),null);});
